package com.banglaselfie.quoteapp;

import android.os.Build;

public class ActivityConfig {


    public static String ADMOB_APP_ID = "";
    public static String ADMOB_BANNER = "";
    public static String ADMOB_INTERSTITIAL = "";

    public static String SOCIAL_TWITTER = "banglacaption";
    public static String SOCIAL_FACEBOOK = "banglacaption";
    public static String SOCIAL_INSTAGRAM = "banglacaption";

    //This is title for category - total should be X items
    static String[] CATEGORY_NAME = {
            "Happiness Captions",
            "Travel Captions",
            "Inspiring Captions",
            "Smile Captions",
            "Love Captions",
            "Life Quotes",
            "Friendship Status",
            "Success Quotes",
            "Deep Meaningful Captions",
            "Mother and Son Captions",
            "Attitude Caption",
            "Sad Caption",
    };
    //This is image for category - total should be X images
    static int[] CATEGORY_IMAGE = {
            R.drawable.happy,
            R.drawable.travel,
            R.drawable.cat_inspiring,
            R.drawable.aaaa,
            R.drawable.love,
            R.drawable.lifequotes,
            R.drawable.cat_friendship,
            R.drawable.success,
            R.drawable.deepmeaning,
            R.drawable.mother,
            R.drawable.attitude,
            R.drawable.cat_depression,


    };

    //This is background image - can have any number of images.
    public static int[] RANDOM_IMAGE = {
            R.drawable.bg_quote_one,
            R.drawable.bg_quote_two,
            R.drawable.bg_quote_three,
            R.drawable.bg_quote_four,
            R.drawable.bg_quote_five,
            R.drawable.bg_quote_six,
            R.drawable.bg_quote_seven,
            R.drawable.bg_quote_eight,
            R.drawable.bg_quote_nine,
            R.drawable.bg_quote_ten,
            R.drawable.bg_quote_eleven,
    };


    static String[][] ALL_CATEGORIES = new String[][]{

            //Happiness Captions
            new String[]{
                    "A smile is a curve that sets everything straight.",
                    "A good family is priceless",
                    "Be Happy, Be Bright, Be You.",
                    "Happiness is a selfie with friends.",
                    "Stay true to you and you will end up incredibly happy.",
                    "Sometimes life can surprise you with a happy coincidence.",
                    "Life is short…Smile when you still have teeth.",
                    "Finals are OVER!!!",
                    "I feel the best when I am happy.",
                    "Dream as if you'll live forever, live as if you'll die today -- James Dean",
                    "Doing what you like is freedom. Liking what you do is happiness--Frank Tyger",
                    "Be happy with what you have. Be excited about what you want--Alan Cohen",
                    "Life is a journey, and if you fall in love with the journey, you will be in love forever-- Peter Hagerty",
                    "I've learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel-- Maya Angelou",
                    "Much of the stress that people feel doesn't come from having too much to do. It comes from not finishing what they've started-- David Allen",
                    "We forge the chains we wear in life-- Charles Dickens",
                    "If you look to others for fulfillment, you will never be fulfilled. If your happiness depends on money, you will never be happy with yourself. Be content with what you have; rejoice in the way things are. When you realize there is nothing lacking, the world belongs to you-- Lao Tzu",
                    "Everything is a gift of the universe--even joy, anger, jealously, frustration, or separateness. Everything is perfect either for our growth or our enjoyment-- Ken Keyes Jr",
                    "There is no such thing as a problem without a gift for you in its hands. You seek problems because you need their gifts-- Richard Bach",
                    "If you want to be happy, set a goal that commands your thoughts, liberates your energy, and inspires your hopes--Andrew Carnegie",
                    "Tension is who you think you should be, relaxation is who you are-- Chinese Proverb",
                    "For me it is sufficient to have a corner by my hearth, a book, and a friend, and a nap undisturbed by creditors or grief-- Fernandez de Andrada",
                    "You cannot judge what should bring others joy, and others cannot judge what should bring you joy-- Alan Cohen",
                    "The art of living lies less in eliminating our troubles than growing with them-- Bernard M. Baruch",
                    "Our capacity to draw happiness from aesthetic objects or material goods in fact seems critically dependent on our first satisfying a more important range of emotional or psychological needs, among them the need for understanding, for love, expression and respect-- Alain De Botton",
                    "If you start to think the problem is 'out there,' stop yourself. That thought is the problem--Stephen Covey",
                    "Happiness cannot be traveled to, owned, earned, worn or consumed. Happiness is the spiritual experience of living every minute with love, grace, and gratitude-- Denis Waitley",
                    "Happiness is not a station you arrive at, but a manner of traveling-- Margaret Lee Runbeck",
                    "Security is when everything is settled, when nothing can happen to you; security is the denial of life-- Germaine Greer",

},

            //Travel Captions
            new String[]{
                    "Life is not meant to be in one place.",
                    "Until you step into the unknown, you don’t know what you’re made of.",
                    "Always say yes to new adventures..",
                    "Life is short and the world is wide. I better get started..",
                    "When I’m exploring the world is when I feel most at home.",
                    "Maybe you can’t buy happiness, but you can buy plane tickets.",
                    "I am one of those who never knows the direction of my journey until I have almost arrived. —Anna Louise Strong",
                    "A journey of a thousand miles begins with a single step. —Lao Tzu,",
                    "One’s destination is never a place but rather a new way at looking at things. —Henry Miller",
                   " The gladdest moment in human life is a departure into unknown lands. – Sir Richard Burton",
                    "Be fearless in the pursuit of what sets your soul on fire – Jennifer Lee",
                    " Travel makes one modest. You see what a tiny place you occupy in the world.-Gustav Flaubert",
                    "Traveling – it leaves you speechless, then turns you into a storyteller. – Ibn Battuta",
                    "Better to see something once than hear about it a thousand times",
                    " Adventure may hurt you but monotony will kill you.",
                    "Don’t listen to what they say. Go see.",
                    "All you need to know is that it’s possible. -Wolf, an Appalachian Trail Hiker",
                    "To Travel is to Live – Hans Christian Andersen",
                    "The life you have led doesn’t need to be the only life you have. – Anna Quindlen",
                    " The most beautiful in the world is, of course, the world itself.-Wallace Stevens",
                    "Work, Travel, Save, Repeat",
                    "The journey not the arrival matters. –T.S. Eliot",
                    "Life is short and the world is wide",
                    "Dare to live the life you’ve always wanted.",
                    "Travel and change of place impart new vigor to the mind. – Seneca",
                    "He who would travel happily must travel light.-Antoine de St. Exupery",
                    " And then there is the most dangerous risk of all — the risk of spending your life not doing what you want on the bet you can buy   yourself the freedom to do it later. – Randy Komisar",
                    "No one realizes how beautiful it is to travel until he comes home and rests his head on his old, familiar pillow.– Lin Yutang",
                    "Our battered suitcases were piled on the sidewalk again; we had longer ways to go. But no matter, the road is life. -Jack Kerouac",
                    " Life is either a daring adventure or nothing at all. -Helen Keller",


},

            //Inspiring Captions
            new String[]{

                    "Do one thing every day that scares you. - Eleanor Roosevelt",
                    "We are what we pretend to be, so we must be careful about what we        pretend to be. Kurt Vonnegut.",
                    "What's meant to be will always find a way - Trisha Yearwood",
                    "The flower that blooms in adversity is the rarest and most beautiful of all.-  Walt Disney Company",
                    "It's not the load that breaks you down, it's the way you carry it.- Lou Holtz",
                    "Life is too short to waste your time on people who don’t respect, appreciate, and value you-      Roy T. Bennett.",
                    "Make improvements, not excuses. Seek respect, not attention.- Roy T. Bennett",
                    "Follow your heart, listen to your inner voice, stop caring about what others think.- Roy T. Bennett",
                    "It's hard to beat a person who never gives up.- George Herman Ruth,",
                    "Risks must be taken because the greatest hazard in life is to risk nothing.- Leo F. Buscaglia.",
                    "If you want to achieve greatness stop asking for permission. --Anonymous",
                    "Things work out best for those who make the best of how things work out. --John Wooden",
                    "To live a creative life, we must lose our fear of being wrong.--Anonymous",
                    "If you are not willing to risk the usual you will have to settle for the ordinary.--Jim Rohn",
                    "Trust because you are willing to accept the risk, not because it's safe or certain. --Anonymous",
                    "Take up one idea. Make that one idea your life--think of it, dream of it, live on that idea. Let the brain, muscles, nerves, every part of your body, be full of that idea, and just leave every other idea alone. This is the way to success. --Swami Vivekananda",
                    "All our dreams can come true if we have the courage to pursue them.--Walt Disney",
                    "Good things come to people who wait, but better things come to those who go out and get them. --Anonymous",
                    "If you do what you always did, you will get what you always got. --Anonymous",
                    "Success is walking from failure to failure with no loss of enthusiasm.--Winston Churchill",
                    "Just when the caterpillar thought the world was ending, he turned into a butterfly. --Proverb",
                    "Successful entrepreneurs are givers and not takers of positive energy. --Anonymous",
                    "Whenever you see a successful person you only see the public glories, never the private sacrifices to reach them. --Vaibhav Shah",
                    "Opportunities don't happen, you create them --Chris Grosser",
                    "Try not to become a person of success, but rather try to become a person of value --Albert Einstein",
                    "Great minds discuss ideas; average minds discuss events; small minds discuss people --Eleanor Roosevelt",
                    "I have not failed. I've just found 10,000 ways that won't work --Thomas A. Edison",
                    "If you don't value your time, neither will others. Stop giving away your time and talents--start charging for it --Kim Garst",
                    "A successful man is one who can lay a firm foundation with the bricks others have thrown at him --David Brinkley",
                    "No one can make you feel inferior without your consent --Eleanor Roosevelt",

            },

            //Smile Captions
            new String[]{
                    "A smile is the best defense against in an offensive world.",
                    "Nothing you wear is more important than your smile.",
                    "Don’t cry because it’s over, smile because it happened.",
                    "Smile at the obstacle, for it is a bridge.",
                    "Beauty is power; a smile is its sword.",
                    "A smile is the shortest distance between two people.",
                    " Do not cry because it’s over, smile because it happened.",
                    "  Never regret something that once made you smile.",
                    " Whatever comes in my way, I take it with a  smile.",
                    " Always remember to smile. You never know who might be watching.",
                    "If you don’t have a smile, I can always give you one of mine.",
                    "We always have at least one reason to smile.",
                    " A smile is happiness that can be found right under your nose.",
                    "A smile can be the most beautiful thing in life.",
                    " Always try to smile, because your smile can give other people a reason to smile too.",
                    "Don’t forget to smile because smiling is infectious.",
                    "The prettiest thing that you can wear cannot be found in stores or in your closet. The prettiest thing that you can wear is a smile.",
                    "You are never fully dressed without a smile.",
                    " Count your life with smiles, not tears.",
                    "Use your smile to change the world, but no matter what happens, do not let the world change your smile.",
                    " If you can manage to make a person smile, then you can change their whole world.",
                    "A smile may take just a moment, but the memory of that smile can last forever.",
                    "Keep on smiling because life is beautiful and there is so much to smile about.",
                    "Be the reason that someone has a smile on their face today.",
                    "When you smile it means that you can See Miracles In Life Everyday.",
                    "A smile is the most beautiful curve on a woman’s body.",
                    "Your smile looks beautiful on you, you should wear it more often.",
                    "Keep smiling, it makes people wonder what you are up to.",
                    "When you smile, I smile.",
            },

            //Love Captions
            new String[]{
                    "If I know what love is, it is because of you.",
                    "Some hearts understand each other, even in silence.",
                    "Love is when the other person’s happiness is more important than your own.",
                    "Love took slow steps towards your heart..!!",
                    "Every day I spend with you, becomes the best day of my life.",
                    "Love doesn’t need to be perfect, it just needs to be true.",
                    "How amazing is it to find someone who wants to hear about all the things that go on in your head. ",
                    "If loving you is wrong, then I don’t wanna be right.",
                    "Your smile is a key, to my unlock happiness.",
                    "When the heart takes over, the mind can’t do a thing!! ❤ ❤",
                    "I wont deny that I like you. Neither would I admit. 😛",
                    "I will love you forever until the end of time! No matter what you do! Cause you are my forever! And nothing you do will make my stop loving you 😊 ❤",
                    "Place your time and energy on someone who will add sunshine to your life. Life is too short to waste on the wrong one.",
                    "Thank you for coming into my life. For letting me feel this love that I have for you. Because not everybody is as lucky as I am… To be loved by you! 🙂",
                    "You are one of those beautiful things that happened to my life and made my life worthwhile 🙂 🙂",
                    "I will love you forever. No matter what happens I’ll be there. Distance couldn’t take us apart – it will make us closer. B’Coz true love waits & never surrenders… 🙂",
                    "You looking most amazing,wonderful,fantastic,smart,charming, dazzing…",
                    "Every friendship dosen’t change into love but every love begins with friendship.",
                    "I always pray to God to tie us in a sacred knot so that we spend each and every moment together.",
                    "True love is when she talks non- stop and you are still interested in listening to her.",
                    "Don’t love too much, don’t care too much, don’t trust too much; because that too much can hurt you too much..",
                    "I don’t know if I like you or love you, want you or need you, all I know is I love the feeling I get when I’m near you.",
                    "If you expect something in return, It’s called business, not love.",
                    "I dønt hate peøple, I just løve peøple whø løve me",
                    "Insomnia can be a blessing if you have someone to talk with, the whole night..",
                    "You may be someone to the world but you are the world for someone. ♥ 🙂",
                    "I don’t need a burning sun and a cooling moon to show me my way. Just want you to hold me whenever I tumble.",
                    "Everyone thinks that love hurts.. But love never hurts.. Rejection hurts.. Loneliness hurts.. Love is the only feeling which covers all the pain…",
                    "Love does not consists of gazing at each other, but in looking together in the same direction.",
                    "Bees love honey…people love money…but I LOVE YOU",
                    "Psychology says, you relaize you love someone when you want them to be happy, even if its not with you",


            },
            //Life Quotes
            new String[]{
                    "Get busy living or get busy dying.",
                    "Never let the fear of striking out keep you from playing the game.",
                    "Money and success don’t change people; they merely amplify what is already there.",
                    "Not how long, but how well you have lived is the main thing.",
                    "In order to write about life first you must live it.",
                    "Curiosity about life in all of its aspects, I think, is still the secret of great creative people.",
                    "The unexamined life is not worth living..",
                    "Turn your wounds into wisdom..",
                    "Don’t settle for what life gives you; make life better and build something..",
                    "You will face many defeats in life, but never let yourself be defeated.-Maya Angelou",
                    "The greatest glory in living lies not in never falling, but in rising every time we fall. -Nelson Mandela",
                    "In the end, it's not the years in your life that count. It's the life in your years. -Abraham Lincoln",
                    "Never let the fear of striking out keep you from playing the game. -Babe Ruth",
                    "Life is either a daring adventure or nothing at all. -Helen Keller",
                    "Many of life's failures are people who did not realize how close they were to success when they gave up.-Thomas A. Edison",
                    "You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose. -Dr. Seuss",
                    "If life were predictable it would cease to be life and be without flavor. -Eleanor Roosevelt",
                    "In the end, it's not the years in your life that count. It's the life in your years. -Abraham Lincoln",
                    "Life is a succession of lessons which must be lived to be understood. -Ralph Waldo Emerson",
                    "You will face many defeats in life, but never let yourself be defeated. -Maya Angelou",
                    "Never let the fear of striking out keep you from playing the game. -Babe Ruth",
                   " Life is never fair, and perhaps it is a good thing for most of us that it is not. -Oscar Wilde",
                   "The only impossible journey is the one you never begin. -Tony Robbins",
                    "In this life we cannot do great things. We can only do small things with great love. -Mother Teresa",
                    "Only a life lived for others is a life worthwhile. -Albert Einstein",
                    "The purpose of our lives is to be happy. -Dalai Lama",
                    "Life is what happens when you're busy making other plans. -John Lennon",
                    "You only live once, but if you do it right, once is enough. -Mae West",
                    "Live in the sunshine, swim the sea, drink the wild air. -Ralph Waldo Emerson",
                    "Go confidently in the direction of your dreams! Live the life you've imagined. -Henry David Thoreau",
                    "The greatest glory in living lies not in never falling, but in rising every time we fall. -Nelson Mandela"
            },
            //Friendship Status
            new String[]{
                    "A circle is round it has no end, that’s how long I want to be your friend.",
                    "Having  a best friend who is like your other half.",
                    "Deep conversations with the right people are priceless.",
                    "A friend is someone who makes it easy to believe in yourself.",
                    "If friendship is your weakest point, then you are the strongest person in this world. ",
                    "The better part of one’s life consists of his friendships.",
                    "The language of friendship is not words but meanings.",
                    "Friendship is always a sweet responsibility, never an opportunity",
                    "Wishing to be friends is quick work, but friendship is a slow ripening fruit.",
                    "When worst comes to worst, squad comes first.",
                    "No friendship is an accident.",
                    "Your vibe attracts your tribe.",
                    "As soon as I saw you I knew a grand adventure was about to happen.",
                    "Only one player is not important. The most important thing is the squad, and it’s important to be together. You can’t just lose it over one player.",
                    "You don’t need a King to be Queen.",
                    "What matters is getting the best out of the squad you have.",
                    "You simply cannot do epic things with boring people.",
                    "Friends that travel together stay together.",
                    "I roam fearlessly since I have my squad always geared up.",
                    "We’re like the super friends. We’re a highly animated group.",
                    "I like you because you join in on my weirdness.",
                    "Real men don’t take selfies.",
                    "Sweatpants, hair tied and chilling with no makeup on.",
                    "Sitting silently beside a friend who is hurting may be the best gift we can give.",
                    "Even WiFi-less areas are heaven when each one of my squad is given.",
                    "Squad means family and family means nobody gets left behind.",
                    "Find your tribe. Love them hard.",
                    "When worst comes to worst, squad comes first.",
                    "One million memories. Ten thousand jokes. One hundred shared secrets. One reason: Best friends",
                    "Friends are cure to our blues.",
                    "Love is beautiful, friendship is better.",
            },
            //Success Quotes
            new String[]{
                    "Action is the foundational key to all success.",
                    "If you want to make an easy job seem mighty hard, just keep putting off doing it.",
                    "The successful man is the one who finds out what is the matter with his business before his competitors do.",
                    "Victory is sweetest when you've known defeat.",
                    "The successful man is the one who finds out what is the matter with his business before his competitors do.",
                    "Success does not consist in never making mistakes but in never making the same one a second time.",
                    "I attribute my success to this: I never gave or took any excuse.",
                    "Amateurs sit and wait for inspiration, the rest of us just get up and go to work. ",
                    " The distance between insanity and genius is measured only by success.",
                    "Success is not final; failure is not fatal: It is the courage to continue that counts.-- Winston S. Churchill",
                    "It is better to fail in originality than to succeed in imitation.-- Herman Melville",
                    "The road to success and the road to failure are almost exactly the same.-- Colin R. Davis",
                    "Success usually comes to those who are too busy to be looking for it.-- Henry David Thoreau",
                    "Opportunities don't happen. You create them.-- Chris Grosser",
                    "Don't be afraid to give up the good to go for the great.--John D. Rockefeller",
                    "I find that the harder I work, the more luck I seem to have.-- Thomas Jefferson",
                    "There are two types of people who will tell you that you cannot make a difference in this world: those who are afraid to try and those who are afraid you will succeed.-- Ray Goforth",
                    "Successful people do what unsuccessful people are not willing to do. Don't wish it were easier; wish you were better.-- Jim Rohn",
                    "Try not to become a man of success. Rather become a man of value.-- Albert Einstein",
                    "Never give in except to convictions of honor and good sense.-- Winston Churchill",
                    "Stop chasing the money and start chasing the passion.-- Tony Hsieh",
                    "Success is walking from failure to failure with no loss of enthusiasm.-- Winston Churchill",
                    "I owe my success to having listened respectfully to the very best advice, and then going away and doing the exact opposite.-- G. K. Chesterton",
                    "Would you like me to give you a formula for success? It's quite simple, really: Double your rate of failure. You are thinking of failure as the enemy of success. But it isn't at all. You can be discouraged by failure or you can learn from it, so go ahead and make mistakes. Make all you can. Because remember that's where you will find success.-- Thomas J. Watson",
                    "If you are not willing to risk the usual, you will have to settle for the ordinary.-- Jim Rohn",
                    "The ones who are crazy enough to think they can change the world, are the ones that do.-- Anonymous",
                    "Do one thing every day that scares you.-- Anonymous",
                    "All progress takes place outside the comfort zone.-- Michael John Bobak",
                    "People who succeed have momentum. The more they succeed, the more they want to succeed, and the more they find a way to succeed. Similarly, when someone is failing, the tendency is to get on a downward spiral that can even become a self-fulfilling prophecy.-- Tony Robbins",
            },
            //Deep Meaningful Captions
            new String[]{
                    "Work for a cause, not for applause. Live life to express, not to impress.",
                    "Challenges are what make life interesting. Overcoming them is what makes life meaningful.",
                    "The more you know who you are, and what you want, the less you let things upset you.",
                    "Life is not about waiting for the storm to pass but learning to dance in the rain.",
                    "Be strong but not rude. Be kind but not weak. Be bold but don’t bully. Be humble but not timid. Be confident but not arrogant.",
                    "Doubt kills more dreams than failure ever will.",
                    "A ship in harbor is safe, but that is not what ships are built for.",
                    "The less you respond to negative people, the more peaceful your life will become.",
                    "We have all a better guide in ourselves, if we would attend to it, than any other person can be.– Jane Austen",
                    "Without self knowledge, without understanding the working and functions of his machine, man cannot be free, he cannot govern himself and he will always remain a slave.”– G.I. Gurdijieff",
                    "A human being has so many skins inside, covering the depths of the heart. We know so many things, but we don’t know ourselves! Why, thirty or forty skins or hides, as thick and hard as an ox’s or bear’s, cover the soul. Go into your own ground and learn to know yourself there.– Meister Eckhart",
                    "The more I read, the more I acquire, the more certain I am that I know nothing.– Voltaire",
                    "It is a sad fate for a man to die too well known to everybody else, and still unknown to himself.– Francis Bacon",
                    "To realize that you do not understand is a virtue; not to realize that you do not understand is a defect.– Lao Tzu",
                    "Being deeply loved by someone gives you strength, while loving someone deeply gives you courage.– Lao Tzu",
                    "There is always some madness in love. But there is also always some reason in madness.”– Friedrich Nietzche",
                    "You know you’re in love when you can’t fall asleep because reality is finally better than your dreams.– Dr. Seuss",
                    "Love is that condition in which the happiness of another person is essential to your own.– Robert Heinlein",
                    "I love you as certain dark things are to be loved, in secret, between the shadow and the soul.– Pablo Neruda",
                    "Love looks not with the eyes, but with the mind. And therefore is winged Cupid painted blind.– William Shakespeare",
                    "The opposite of love is not hate, it’s indifference. The opposite of art is not ugliness, it’s indifference. The opposite of faith is not heresy, it’s indifference. And the opposite of life is not death, it’s indifference.– Elie Wiesel",
                    "Painting is poetry that is seen rather than felt, and poetry is painting that is felt rather than seen.– Leonardo da Vinci",
                    "A man should hear a little music, read a little poetry, and see a fine picture every day of his life, in order that worldly cares may not obliterate the sense of the beautiful which God has implanted in the human soul.– Johann Wolfgang von Goethe",
                    "Art enables us to find ourselves and lose ourselves at the same time.– Thomas Merton",
                    "Art is the lie that enables us to realize the truth.– Pablo Picasso",
            },
            //Mother and Son Captions
            new String[]{
                    "It takes one woman twenty years to make a man of her son – and another woman twenty minutes to make a fool of him.",
                    "That strong mother doesn’t tell her cub, Son, stay weak so the wolves can get you. She says, Toughen up, this is reality we are living in.",
                    " Even more than the time when she gave birth, a mother feels her greatest joy when she hears others refer to her son as a wise learned one.",
                    "A man never sees all that his mother has been to him until it’s too late to let her know that he sees it.",
                    "When Jack Burns needed to hold his mother’s hand, his fingers could see in the dark. ",
                    "There has never been, nor will there ever be, anything quite so special as the love between the mother and a son.",
                    " Happy  is the son whose faith in his mother remains unchallenged.",
                    " A  son is a mother’s most precious treasure.",
                    "I cannot be more grateful for the things that I have because I love my son and I have him.",
                    "I constantly go between wanting you to be my baby forever, and being excited about all the amazing things you’ll do in this life.",
                    "Superheroes are often disguised as sons.",
                    "To a mother, a son is never a fully grown man; and a son is never a fully grown man until he understands and accepts this about his mother.",
                    "Never has it been more apparent that the days of my baby boy’s childhood are fleeting.",
                    "The only man who has stolen my heart is my son.",
                    "I have a son, who is my heart. A wonderful young man, daring and loving and strong and kind.",
                    "No matter how old you get, you will always have my hand to hold. I will always be here to give you the support that you need. I love you, son.",
                    "Mother gives her hand to a son only for a while, and she presents him her heart for life.",
                    "I love my son and he makes me proud and brings me happy whenever he’s around me.",
                    "Let your boys test their wings. They may not be eagles, but that doesn’t mean they shouldn’t soar free.",
                    "My son, you are the reason that I am living today. You’re my world. I have been struggling for a long in my life to provide you comfort, and I’ll always be doing the same for you till my last. I love you!",
                    "No matter your age, you always need your mom.",
                    "I hope you know how special you are. You will go places, just believe in yourself. I will be right here cheering you on. I love you!",
                    "You can be naughty at times, but you are mostly sweet and nice. Never lose your kindness and your compassion for others.In this oftentimes cruel world, we need more nice guys like you! Keep doing us proud, son!",
                    "Until you have a son of your own… you will never know the joy, the love beyond feeling that resonates in the heart of a father as he looks upon his son.",
                    "My son’s the most precious thing to me; he’s changed me from being selfish to selfless.",
                    "Sons may grow into men and grow out of their toys but in the hearts of mothers, they are still their little boys.",
                    "I just want you to be bold and brave in life. Live your life to the fullest. I don’t want you to regret anything when you’re old and gray. I love you son!",
                    "Only mother is able to teach her son how to love.",
                    "It doesn’t matter what problems follow a man; he always knows that he is the best for her mother.",
                    "I’m thankful for my son’s laughter. It’s the sound of all that’s right in the world.",
                    "The best way for a woman to get away from the problems is to see her son`s smile.",
                    "I think you might have been an angel sent by the heavens above to me, you make me happy.",
                    "The hardest thing for every mother is to teach her son to bite the bullet and keep going ahead."
            },
            //Attitude Caption
            new String[]{
                    "I’m only responsible for what I say not for what you understand… ",
                    "I burned by bridges so the devil couldn’t follow me.  ",
                    "I am the one who can give you surprises and shocks at the same. ",
                    "Happiness depends on your mindset and attitude.  ",
                    "Keep your face towards the sunshine, you will never see the shadow. ",
                    "The only thing worse than a boy who hates you: a boy that loves you.   ",
                    "Silent people have the loudest minds.   ",
                    "Attitude is a lot like pregnancy. You can try to hide it all you want, but eventually, it will come out.  ",
                    "A positive attitude will lead to positive outcomes.  ",
                    "I hear them talking behind my back, at least there is a reason why they are behind me.  ",
                    "Lay a firm foundation with the bricks that others throw at you    ",
                    "Awesome ends with ME and Ugly starts with you. ",
                    "If you don’t like my attitude than you have problems with your choice.",
                    "Positive expectations are the mark of the superior personality. ",
                    "Winners focus on winning, losers focus on winners  ",
                    "Don’t run after him who tries to avoid you..!   ",
                    "en are born to succeed, not to fail. ",
                    "When life throws a rock at you, throw back a brick ",
                    "I don’t have a dirty mind, I have a sexy imagination.",
                    "I’m a humble person, really. I’m actually much greater than I think I am. ",
                    "Attitude is like a wristwatch. Every watch shows different time than other and everyone thinks his watch is showing the right time. ",
                    "Don’t get my personality and my attitude twisted, because my personality is me, and my attitude depends on you! ",
                    "Change ‘ONE DAY’ into ‘TODAY  ",
                    "When life gives you lemons, make lemonade ",
                    "No, I’m not feeling violent, I’m feeling creative with weapons. ",
                    "Why chase you when I’m the catch. ",
                    "A negative attitude is nine times more powerful than a positive attitude.",
                    "Don’t change so people will like you. Be yourself and the right people will love the real you.",
                    "I don’t have an attitude problem, you have a perception problem.  ",
                    "A man who is a master of patience is master of everything else.  ",
                    "My Life. My Rules. & My Attitude ",
                    "I haven’t changed. I grew up. Maybe you should give it a try sometime. ",
                    "What good are wings without the courage to fly? ",
                    "I can’t change my personality. I’ll always smile, but I’ll be more focused.",
                    "I am not perfect but I am limited edition. ",
                    "Excellence is not a skill, it’s an attitude.  ",
                    "My style is what “I like” not what “Others like”  ",
                    "I may be fat, but you’re ugly. And I can lose weight!  ",
                    "Fire is the test of gold; adversity, of strong men. ",
                    "There can be no positive result through a negative attitude. Think positive. Live positive.",
            },
            //Sad Caption
            new String[]{
                    "   My tears are like anchors that sink my heart to the depths of the deepest ocean…. ",
                    " It hurts when you have someone in your heart but can’t have in your arms. ",
                    "Everybody is going to hurt you you just gotta find the ones worth suffering for.  ",
                    " I am not worthy of being in love… ",
                    " I’m lost without love.   ",
                    " It’s hard to forget someone who gave you so much to remember.   ",
                    "I fought to keep your love,you didn�t fight to keep mine.That�s the difference between you and me.   ",
                    "I don’t understand the love at all..I guess it;s beauty is only at the beginning..  ",
                    "I never stopped loving you, I just stopped showing it    ",
                    "If you leave without a reason dont come back with an excuse.      ",
                    " I did everything right for someone that does everything wrong..    ",
                    "It sucks how some people use you when they need you and then they put you aside like you didn’t even matter to them from the beginning…  ",
                    "Love is the person you think about during the sad songs…  ",
                    "Temporary happiness isn’t worth long term pain…  ",
                    " I was born the day you kissed me, and I died inside the night you left me. But I lived, oh how I lived while you loved me. ",
                    "Silence is the most powerful scream.        ",
                    "People walk away easily but they leave their memories with us forever…  ",
                    " Did I change or did you just stop loving me…      ",
                    "The most important part of moving on is letting go.     ",
                    "If I die tomorrow u will miss me   ",
                    "Don’t cry for the person who doesn’t know the value of your tears",
                    "Stop waiting for someone’s text",
                    "I still care, that ‘s the problem",
                    "Please don’t interrupt me while I’m ignoring you",
                    "Missing someone hurts, but whats hurts even more, is knowing that you’r the reason that they’re gone",
                    "You get no appreciation when you are nice, but people notice when you become bad",
                    "You will know a person’s heart by the way they treat their pets",
                    "I may smile and i may laugh. But deep down my heart is a pain you’ll never guess",
                    "Lonely is not being alone. It’s the feeling that no one cares",
                    "One gets used to being alone, but it’s enough to break it for a day & you have to get used to it again from the beginning",
                    "People are lonely because they build walls instead of bridges",
                    "Sometimes It’s better to be alone… No one can hurt you",
                    "Standing alone is better than standing with people who don’t value you",
                    "The loneliest moment in someone’s life is when they are watching their whole world fall apart, and all they do is stare blankly",
                    "The person who keeps tries to keep everyone happy often ends up feeling the loneliest",
                    "You are always there for me and so you give me the courage to stand alone",
                    "You can’t be strong all the time. Sometimes you just need to be alone and let your tears out",
                    "A breakup is like a broken mirror. It’s better to leave it than hurt yourself trying to pick up the pieces",
                    "A part of me will be waiting for you for a lifetime",
                    "A relationship is only made for two, but some just forget how to count",
                    "As soon as forever is through, I’ll be over you",
            },

    };
}